# Generated by Django 3.1.3 on 2020-11-19 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating',
            name='car',
        ),
        migrations.AlterField(
            model_name='car',
            name='make_id',
            field=models.IntegerField(max_length=24),
        ),
        migrations.AlterField(
            model_name='car',
            name='model_id',
            field=models.IntegerField(max_length=25, primary_key=True, serialize=False, unique=True),
        ),
        migrations.DeleteModel(
            name='AccessRecord',
        ),
        migrations.DeleteModel(
            name='Rating',
        ),
    ]
