# Generated by Django 2.1.15 on 2020-11-15 10:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccessRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('make_id', models.CharField(max_length=24)),
                ('make_name', models.CharField(max_length=100)),
                ('model_id', models.CharField(max_length=25, primary_key=True, serialize=False, unique=True)),
                ('model_name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_rating', models.IntegerField(choices=[(1, 'Poor'), (2, 'Below Average'), (3, 'Average'), (4, 'Good'), (5, 'Excellent')])),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Car')),
            ],
        ),
        migrations.AddField(
            model_name='accessrecord',
            name='car_record',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Rating'),
        ),
    ]
